[package]
name = "zi-tui"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
ratatui = { version = "0.26.1", features = ["unstable"] }
anyhow = { workspace = true }
tracing = { workspace = true }

