[package]
name = "zi"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
bitflags = { workspace = true }
futures-core = { workspace = true }
parking_lot = { workspace = true }
rustc-hash = { workspace = true }
regex-cursor = { workspace = true }
slotmap = "1.0.7"
tokio = { workspace = true, default-features = false, features = ["sync", "rt-multi-thread", "time", "macros", "fs"] }
tracing = { workspace = true }
tree-sitter = { workspace = true, features = ["wasm"] }
unicode-width = "0.1.11"
wasmtime = { version = "19", features = ["component-model"] }
tui = { path = "../zi-tui", package = "zi-tui" }
nucleo = "0.5.0"
ignore = "0.4.22"
rayon = "1.9.0"
chumsky = "0.9.3"
crossterm = { workspace = true, optional = true }
futures-util = { workspace = true }
directories-next = "2.0.0"
smol_str = "0.2.1"
tokio-stream = { version = "0.1.15", default-features = false, features = ["fs"] }
arbitrary = { version = "1.3.2", optional = true, features = ["derive"] }
grep = "0.3.1"
async-trait = { workspace = true }
stdx = { workspace = true }
zi-core = { workspace = true, features = ["tree-sitter"] }
zi-lsp = { workspace = true }
zi-text = { workspace = true }
zi-textobject = { workspace = true }
content_inspector = "0.2.4"
dyn-clone = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
datatest-stable = "0.2.3"
duct = "0.13.7"
proptest = "1.4.0"
tempfile = "3.10.0"
test-strategy = "0.3.1"
futures-executor = "0.3.30"
zi = { path = ".", features = ["arbitrary"] }
zi-nvim = { path = "../zi-nvim" }
regex = "1"

[features]
arbitrary = ["dep:arbitrary", "bitflags/arbitrary", "zi-core/arbitrary"]

[[test]]
name = "regression"
harness = false

[[test]]
name = "nvim"
harness = false
