[package]
name = "zi"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.80"
bitflags = "2.4.2"
futures-core = "0.3.30"
parking_lot = "0.12.1"
ropey = "1.6.1"
rustc-hash = "1.1.0"
slotmap = "1.0.7"
tokio = { version = "1.36.0", default-features = false, features = [
    "sync",
    "rt-multi-thread",
] }
tracing = "0.1.40"
tree-sitter = "0.20.4"
tree-sitter-go = "0.20.0"
tree-sitter-json = "0.20.2"
tree-sitter-rust = "0.20.4"
tree-sitter-toml = "0.20.0"
unicode-width = "0.1.11"
wasmtime = { version = "17.0.1", features = ["component-model"] }
wit-bindgen = "0.18.0"
zi-lsp = { path = "../zi-lsp" }
tui = { path = "../zi-tui", package = "zi-tui" }
nucleo = "0.4.0"
ignore = "0.4.22"
rayon = "1.9.0"
stdx = { path = "../stdx", features = ["ropey"] }
chumsky = "0.9.3"
crossterm = { version = "0.27.0", optional = true }
expect-test = "1.4.1"
memmap2 = "0.9.4"
memchr = "2.7.1"

[dev-dependencies]
proptest = "1.4.0"
tempfile = "3.10.0"
test-strategy = "0.3.1"
