[package]
name = "zi"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.80"
bitflags = "2.4.2"
crossterm = "0.27.0"
futures-core = "0.3.30"
parking_lot = "0.12.1"
ratatui = { version = "0.26.1", default-features = false }
ropey = "1.6.1"
rustc-hash = "1.1.0"
slotmap = "1.0.7"
tokio = { version = "1.36.0", default-features = false, features = ["sync"] }
tracing = "0.1.40"
tree-sitter = "0.20.4"
tree-sitter-go = "0.20.0"
tree-sitter-json = "0.20.2"
tree-sitter-rust = "0.20.4"
tree-sitter-toml = "0.20.0"
unicode-width = "0.1.11"
wasmtime = { version = "17.0.1", features = ["component-model"] }
wit-bindgen = "0.18.0"
zi-lsp = { version = "0.1.0", path = "../zi-lsp" }
tui = { version = "0.1.0", path = "../zi-tui", package = "zi-tui" }
nucleo = "0.4.0"
ignore = "0.4.22"

[dev-dependencies]
tempfile = "3.10.0"
tokio = { version = "1.36.0", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }
