[package]
name = "zi"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.80"
bitflags = "2.4.2"
futures-core = "0.3.30"
parking_lot = "0.12.1"
rustc-hash = "1.1.0"
slotmap = "1.0.7"
tokio = { version = "1.36.0", default-features = false, features = ["sync", "rt-multi-thread", "time", "macros", "fs"] }
tracing = "0.1.40"
tree-sitter = { version = "0.22.1", features = ["wasm"] }
unicode-width = "0.1.11"
wasmtime = { version = "18.0.2", features = ["component-model"] }
zi-lsp = { path = "../zi-lsp" }
tui = { path = "../zi-tui", package = "zi-tui" }
nucleo = "0.4.0"
ignore = "0.4.22"
rayon = "1.9.0"
stdx = { path = "../stdx" }
chumsky = "0.9.3"
crossterm = { version = "0.27.0", optional = true }
expect-test = "1.4.1"
memmap2 = "0.9.4"
memchr = "2.7.1"
smallvec = "2.0.0-alpha.4"
async-trait = "0.1.77"
futures-util = "0.3.30"
directories-next = "2.0.0"
smol_str = "0.2.1"
tokio-stream = { version = "0.1.15", default-features = false, features = ["fs"] }
arbitrary = { version = "1.3.2", optional = true, features = ["derive"] }
crop = { version = "0.4.2", features = ["graphemes"] }

[dev-dependencies]
datatest-stable = "0.2.3"
duct = "0.13.7"
proptest = "1.4.0"
tempfile = "3.10.0"
test-strategy = "0.3.1"
futures-executor = "0.3.30"
zi = { path = ".", features = ["arbitrary"] }
nvim-rs = { version = "0.7.0", features = ["use_tokio"] }

[features]
arbitrary = ["dep:arbitrary", "bitflags/arbitrary"]

[[test]]
name = "regression"
harness = false

[[test]]
name = "nvim"
harness = false
