package zi:api;

world plugin {
    import editor;
    use editor.{mode};

    export initialize: func();
}

interface editor {
    variant mode {
        normal,
        insert,
    }

    type line = u32;
    type col = u32;

    record position {
       line: line,
       col: col,
    }

    get-mode: func() -> mode;
    set-mode: func(mode: mode) -> ();
}


