package zi:api;

world plugin {
    import editor;

    use editor.{mode};

    type name = string;

    export initialize: func();
    export get-name: func() -> name;
    export dependencies: func() -> list<name>;
    export handler: func() -> command-handler;

    resource command-handler {
        constructor();
        exec: func(cmd: string, args: list<string>) -> ();
    }
}

interface editor {
    variant mode {
        normal,
        insert,
        visual,
        command,
    }

    type line = u32;
    type col = u32;

    record position {
       line: line,
       col: col,
    }

    insert: func(text: string) -> ();
    get-mode: func() -> mode;
    set-mode: func(mode: mode) -> ();
    get-active-view: func() -> view;

    create-command: func(cmd: string) -> ();

    resource view {
        get-buffer: func() -> buffer;
        get-cursor: func() -> position;
        set-cursor: func(pos: position) -> ();
    }

    resource buffer {
    }
}


