package zi:api;

world plugin {
    import editor;

    export lifecycle;
    export dependency;
    export command;
}

interface dependency {
    get-name: func() -> string;
    dependencies: func() -> list<string>;
}

interface lifecycle {
    use command.{command };

    record initialize-result {
        commands: list<command>,
    }

    initialize: func() -> initialize-result;
    shutdown: func();
}

// This is structured in a very particular way to get bindgen to do what we want (on both host and guest side).
// - Do not use anything from this interface in the main `world` otherwise the host will generate useless bindings.
// - If this is not in separate interface (and in the main world) we have the above issue + the guest doesn't generate bindings for this.
interface command {
    record arity {
        min: u8,
        max: u8,
    }

    flags command-flags {
        range,
    }

    record command {
        name: string,
        arity: arity,
        opts: command-flags,
    }

    variant command-error {
        message(string),
    }

    resource handler {
        constructor();
        exec: func(cmd: string, args: list<string>, force: bool) -> result<_, command-error>;
    }
}

interface editor {
    variant operator {
        delete,
        change,
        yank,
    }

    variant mode {
        normal,
        insert,
        visual,
        command,
        replace-pending,
        operator-pending(operator),
    }

    variant edit-error {
        readonly,
    }

    type line = u32;
    type col = u32;

    record point {
       line: line,
       col: col,
    }

    insert: func(text: string) -> result<_, edit-error>;
    get-mode: func() -> mode;
    set-mode: func(mode: mode);
    get-active-view: func() -> view;

    save-all: func(force: bool) -> result<_, string>;
    reload: func() -> result<_, string>;
    open-jump-list: func();
    open-file-explorer: func(path: string);
    set-option: func(key: string, value: string) -> result<_, string>;

    enum direction {
        left,
        right,
        up,
        down,
    }

    enum vertical-alignment {
        top,
        center,
        bottom,
    }

    flags buffer-flags {
        readonly,
        dirty,
    }

    resource view {
        get-buffer: func() -> buffer;
        get-cursor: func() -> point;
        set-cursor: func(pos: point);
        close: func();
        save: func(force: bool) -> result<_, string>;
        inspect: func();
        insert: func(text: string) -> result<_, edit-error>;
        delete-char: func() -> result<_, edit-error>;
        paste-after: func() -> result<_, edit-error>;
        undo: func() -> result<bool, edit-error>;
        redo: func() -> result<bool, edit-error>;
        scroll: func(direction: direction, amount: u32);
        align: func(alignment: vertical-alignment);
        focus: func();
    }

    resource buffer {
        get-file-path: func() -> option<string>;
        get-flags: func() -> buffer-flags;
        len-lines: func() -> u32;
    }
}


