[package]
name = "zi-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
async-lsp = "0.2.0"
async-process = "2.1.0"
tokio = { version = "1.36.0", features = ["io-util"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
tower = "0.4.13"

[lints]
workspace = true
